apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "permitio.fullname" . }}
  labels:
    {{- include "permitio.labels" . | nindent 4 }}
data:
  schema.yaml: |
    {{- if .Values.schema.mode }}
    mode: {{ .Values.schema.mode }}
    {{- end }}
    resources:
    {{- if .Values.schema.resources }}
    {{- toYaml .Values.schema.resources | nindent 4 }}
    {{- end }}
    roles:
    {{- if .Values.schema.roles }}
    {{- toYaml .Values.schema.roles | nindent 4 }}
    {{- end }}
    implicit_grants:
    {{- if .Values.schema.implicit_grants }}
    {{- toYaml .Values.schema.implicit_grants | nindent 4 }}
    {{- end }}
  data.yaml: |
    tenants:
    {{- if .Values.data.tenants }}
    {{- toYaml .Values.data.tenants | nindent 4 }}
    {{- end }}
    users:
    {{- if .Values.data.users }}
    {{- toYaml .Values.data.users | nindent 4 }}
    {{- end }}
    resource_instances:
    {{- if .Values.data.resource_instances }}
    {{- toYaml .Values.data.resource_instances | nindent 4 }}
    {{- end }}
    relationship_tuples:
    {{- if .Values.data.relationship_tuples }}
    {{- toYaml .Values.data.relationship_tuples | nindent 4 }}
    {{- end }}
    role_assignments:
    {{- if .Values.data.role_assignments }}
    {{- toYaml .Values.data.role_assignments | nindent 4 }}
    {{- end }}
